[32mINFO    [0m test:logging_handler.py:63 登录成功, 账号：17386049001
[1m[31mERROR   [0m root:test_register_shop.py:30 出错了